//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientApp.UITest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextForTesting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextForTesting() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientApp.UITest.TextForTesting", typeof(TextForTesting).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded Prescriptions:.
        /// </summary>
        internal static string DownloadedPrescriptions_en {
            get {
                return ResourceManager.GetString("DownloadedPrescriptions_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code may not be from myHEXplan (code: QRE01).
        /// </summary>
        internal static string ErrorMessage01_en {
            get {
                return ResourceManager.GetString("ErrorMessage01_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR code may have an invalid signature (code: QRE02).
        /// </summary>
        internal static string ErrorMessage02_en {
            get {
                return ResourceManager.GetString("ErrorMessage02_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold over the QR Code printed on your paper prescription.
        /// </summary>
        internal static string HowToScanText_en {
            get {
                return ResourceManager.GetString("HowToScanText_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleansing solution.
        /// </summary>
        internal static string Item1ShoppingList_en {
            get {
                return ResourceManager.GetString("Item1ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposable cups.
        /// </summary>
        internal static string Item2ShoppingList_en {
            get {
                return ResourceManager.GetString("Item2ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterile gauze dressing 2in x 2in (5cm x 5cm).
        /// </summary>
        internal static string Item3ShoppingList_en {
            get {
                return ResourceManager.GetString("Item3ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterile gauze dressing 4in x 4in (10cm x 10cm).
        /// </summary>
        internal static string Item4ShoppingList_en {
            get {
                return ResourceManager.GetString("Item4ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterile cotton swabs.
        /// </summary>
        internal static string Item5ShoppingList_en {
            get {
                return ResourceManager.GetString("Item5ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bag for waste disposal.
        /// </summary>
        internal static string Item6ShoppingList_en {
            get {
                return ResourceManager.GetString("Item6ShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame ID.
        /// </summary>
        internal static string LbFrameId_en {
            get {
                return ResourceManager.GetString("LbFrameId_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on emoticons for setting.
        /// </summary>
        internal static string LblClickOnEmoticons_en {
            get {
                return ResourceManager.GetString("LblClickOnEmoticons_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the time, at your convenience, for receiving pin site care alert notifications..
        /// </summary>
        internal static string LblDailyTimeInfo_en {
            get {
                return ResourceManager.GetString("LblDailyTimeInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable personal goal.
        /// </summary>
        internal static string LblDisableGoal_en {
            get {
                return ResourceManager.GetString("LblDisableGoal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LblDoneTitle_en {
            get {
                return ResourceManager.GetString("LblDoneTitle_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t give up!.
        /// </summary>
        internal static string LblDontGiveUp_en {
            get {
                return ResourceManager.GetString("LblDontGiveUp_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myHEXplan is a travel companion and will give you insights on your treatment. Set the time, at your convenience, for receiving insight messages..
        /// </summary>
        internal static string LblGeneralInfo_en {
            get {
                return ResourceManager.GetString("LblGeneralInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Health is as important as physical health. Think positive! You will only wear this device for a short period of your life.
        /// </summary>
        internal static string LblGeneralMessage_en {
            get {
                return ResourceManager.GetString("LblGeneralMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you experience any of these signs, or if you have doubts on the pin or wire site cleaning procedure, you should contact your surgeon&apos;s office immediately..
        /// </summary>
        internal static string LblGeneralMessageInfection_en {
            get {
                return ResourceManager.GetString("LblGeneralMessageInfection_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is essential that you treat your external fixator with care and maintain clean, dry pin sites to help prevent infection..
        /// </summary>
        internal static string LblHelpInfectionText_en {
            get {
                return ResourceManager.GetString("LblHelpInfectionText_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before starting, be sure that you have everything you need for pin site cleaning.
        /// </summary>
        internal static string LblHelpListText_en {
            get {
                return ResourceManager.GetString("LblHelpListText_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap play to start video tutorial.
        /// </summary>
        internal static string LblHelpVideoText_en {
            get {
                return ResourceManager.GetString("LblHelpVideoText_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap play to start video tutorial.
        /// </summary>
        internal static string LblHelpVideoTutorial_en {
            get {
                return ResourceManager.GetString("LblHelpVideoTutorial_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you see redness at the pin or wire site?.
        /// </summary>
        internal static string LblInfectionQuestion1_en {
            get {
                return ResourceManager.GetString("LblInfectionQuestion1_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you see swelling at the pin or wire site?.
        /// </summary>
        internal static string LblInfectionQuestion2_en {
            get {
                return ResourceManager.GetString("LblInfectionQuestion2_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you see thick or colored discharge from the pin or wire site?.
        /// </summary>
        internal static string LblInfectionQuestion3_en {
            get {
                return ResourceManager.GetString("LblInfectionQuestion3_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you see loosening or movement of the pin or wire?.
        /// </summary>
        internal static string LblInfectionQuestion4_en {
            get {
                return ResourceManager.GetString("LblInfectionQuestion4_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you feel persistent pain or soreness at the pin or wire site?.
        /// </summary>
        internal static string LblInfectionQuestion5_en {
            get {
                return ResourceManager.GetString("LblInfectionQuestion5_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to myHEXplan delivers information throughout your treatment journey, with helpful reminders designed to support the oral and written information your surgeon has provided.
        /// </summary>
        internal static string LblInfoMessage_en {
            get {
                return ResourceManager.GetString("LblInfoMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following preferences can be set anytime from the Settings screen..
        /// </summary>
        internal static string LblInfoPref_en {
            get {
                return ResourceManager.GetString("LblInfoPref_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable insights.
        /// </summary>
        internal static string LblInsights_en {
            get {
                return ResourceManager.GetString("LblInsights_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only wear this device for a short period of your life: remind yourself why you agreed to start this treatment journey..
        /// </summary>
        internal static string LblJourneyRemind_en {
            get {
                return ResourceManager.GetString("LblJourneyRemind_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bored.
        /// </summary>
        internal static string LblMoodBored_en {
            get {
                return ResourceManager.GetString("LblMoodBored_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calm.
        /// </summary>
        internal static string LblMoodCalm_en {
            get {
                return ResourceManager.GetString("LblMoodCalm_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encouraged.
        /// </summary>
        internal static string LblMoodEncouraged_en {
            get {
                return ResourceManager.GetString("LblMoodEncouraged_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frustrated.
        /// </summary>
        internal static string LblMoodFrustrated_en {
            get {
                return ResourceManager.GetString("LblMoodFrustrated_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy.
        /// </summary>
        internal static string LblMoodHappy_en {
            get {
                return ResourceManager.GetString("LblMoodHappy_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am OK.
        /// </summary>
        internal static string LblMoodIamOK_en {
            get {
                return ResourceManager.GetString("LblMoodIamOK_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nervous.
        /// </summary>
        internal static string LblMoodNervous_en {
            get {
                return ResourceManager.GetString("LblMoodNervous_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic.
        /// </summary>
        internal static string LblMoodOptimistic_en {
            get {
                return ResourceManager.GetString("LblMoodOptimistic_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        internal static string LblMoodSad_en {
            get {
                return ResourceManager.GetString("LblMoodSad_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have been treated with a generic external fixation device or have not received a prescription with QR code, start your treatment without digital prescription..
        /// </summary>
        internal static string LblNoPrescription_en {
            get {
                return ResourceManager.GetString("LblNoPrescription_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap play to start video tutorial.
        /// </summary>
        internal static string LblPinSiteCareHelpVideo_en {
            get {
                return ResourceManager.GetString("LblPinSiteCareHelpVideo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following preferences can be set anytime from the Settings screen..
        /// </summary>
        internal static string LblPreferenceInfo_en {
            get {
                return ResourceManager.GetString("LblPreferenceInfo_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following preferences can be set anytime from the Settings screen..
        /// </summary>
        internal static string LblPreferences_en {
            get {
                return ResourceManager.GetString("LblPreferences_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your photo.
        /// </summary>
        internal static string LblSelectPhoto_0_en {
            get {
                return ResourceManager.GetString("LblSelectPhoto_0_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your photo.
        /// </summary>
        internal static string LblSelectPhoto_1_en {
            get {
                return ResourceManager.GetString("LblSelectPhoto_1_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set alert time.
        /// </summary>
        internal static string LblSetDailyTime_en {
            get {
                return ResourceManager.GetString("LblSetDailyTime_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your personal goal.
        /// </summary>
        internal static string LblSetPersonalGoal_en {
            get {
                return ResourceManager.GetString("LblSetPersonalGoal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my daily tasks.
        /// </summary>
        internal static string LblTitleAllMyDailyTask_en {
            get {
                return ResourceManager.GetString("LblTitleAllMyDailyTask_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How are you today?.
        /// </summary>
        internal static string LblTitleHowDoYouFeelToday_en {
            get {
                return ResourceManager.GetString("LblTitleHowDoYouFeelToday_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Am I getting an infection?.
        /// </summary>
        internal static string LblTitleInfection_en {
            get {
                return ResourceManager.GetString("LblTitleInfection_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insight messages.
        /// </summary>
        internal static string LblTitleInsightsMessages_en {
            get {
                return ResourceManager.GetString("LblTitleInsightsMessages_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Diary.
        /// </summary>
        internal static string LblTitleMyDiary_en {
            get {
                return ResourceManager.GetString("LblTitleMyDiary_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal goal.
        /// </summary>
        internal static string LblTitlePersonalGoal_en {
            get {
                return ResourceManager.GetString("LblTitlePersonalGoal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin site care.
        /// </summary>
        internal static string LblTitlePinSiteCare_en {
            get {
                return ResourceManager.GetString("LblTitlePinSiteCare_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin site care.
        /// </summary>
        internal static string LblTitlePinSiteCareSetProfile_en {
            get {
                return ResourceManager.GetString("LblTitlePinSiteCareSetProfile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Prescriptions.
        /// </summary>
        internal static string LblTitlePrescription_en {
            get {
                return ResourceManager.GetString("LblTitlePrescription_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string LblTitlePrescriptionMessage_en {
            get {
                return ResourceManager.GetString("LblTitlePrescriptionMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string LblTitleProfile_en {
            get {
                return ResourceManager.GetString("LblTitleProfile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LblTitleSettings_en {
            get {
                return ResourceManager.GetString("LblTitleSettings_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What do I need?.
        /// </summary>
        internal static string LblTitleShoppingList_en {
            get {
                return ResourceManager.GetString("LblTitleShoppingList_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your treatment.
        /// </summary>
        internal static string LblTitleStartYourTreatment_en {
            get {
                return ResourceManager.GetString("LblTitleStartYourTreatment_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struts adjustment.
        /// </summary>
        internal static string LblTitleStrutAdjust_en {
            get {
                return ResourceManager.GetString("LblTitleStrutAdjust_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string LblTitleSupport_en {
            get {
                return ResourceManager.GetString("LblTitleSupport_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My time-lapse.
        /// </summary>
        internal static string LblTitleTimeLapse_en {
            get {
                return ResourceManager.GetString("LblTitleTimeLapse_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string LblTitleUserDetails_en {
            get {
                return ResourceManager.GetString("LblTitleUserDetails_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User profile.
        /// </summary>
        internal static string LblTitleUserProfile_en {
            get {
                return ResourceManager.GetString("LblTitleUserProfile_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start your treatment.
        /// </summary>
        internal static string LblTitleUserProfileCustomization_en {
            get {
                return ResourceManager.GetString("LblTitleUserProfileCustomization_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to myHEXplan!.
        /// </summary>
        internal static string LblTitleWelcomeUserAnonymous_en {
            get {
                return ResourceManager.GetString("LblTitleWelcomeUserAnonymous_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to myHEXplan!.
        /// </summary>
        internal static string LblTitleWelcomeUserNormal_en {
            get {
                return ResourceManager.GetString("LblTitleWelcomeUserNormal_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To do.
        /// </summary>
        internal static string LblToDoTitle_en {
            get {
                return ResourceManager.GetString("LblToDoTitle_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well done!.
        /// </summary>
        internal static string LblWellDone_en {
            get {
                return ResourceManager.GetString("LblWellDone_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have been treated with TL-HEX and have received a prescription with QR code from your surgeon, scan it to enable myHEXplan for daily struts adjustment and automatic notifications..
        /// </summary>
        internal static string LblWithPrescription_en {
            get {
                return ResourceManager.GetString("LblWithPrescription_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string LbStrutSite_en {
            get {
                return ResourceManager.GetString("LbStrutSite_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be done.
        /// </summary>
        internal static string LbStrutToBeDone_en {
            get {
                return ResourceManager.GetString("LbStrutToBeDone_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Light ON/OFF.
        /// </summary>
        internal static string LedLightState_en {
            get {
                return ResourceManager.GetString("LedLightState_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Prescription(s) for the frame ID A have been published.
        /// </summary>
        internal static string NewPrescriptionAlertMessage_en {
            get {
                return ResourceManager.GetString("NewPrescriptionAlertMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription(s) for the frame ID A have been revoked.
        /// </summary>
        internal static string RevokedPrescriptionAlertMessage_en {
            get {
                return ResourceManager.GetString("RevokedPrescriptionAlertMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription revoked.
        /// </summary>
        internal static string RevokedPrescriptionMessage_en {
            get {
                return ResourceManager.GetString("RevokedPrescriptionMessage_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes you will be tempted to say nothing is happening, because correction happens slowly. Do not give up! Each fruit has its own season..
        /// </summary>
        internal static string TxtBoredMood_en {
            get {
                return ResourceManager.GetString("TxtBoredMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtCalmMood_en {
            get {
                return ResourceManager.GetString("TxtCalmMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are doing great job and the reward is coming soon..
        /// </summary>
        internal static string TxtEncouragedMood_en {
            get {
                return ResourceManager.GetString("TxtEncouragedMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is OK, this long treatment is frustrating. The device is just temporary. Remind yourself about the final goal of treatment and your team is here to support you in achieving that goal..
        /// </summary>
        internal static string TxtFrustratedMood_en {
            get {
                return ResourceManager.GetString("TxtFrustratedMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtHappyMood_en {
            get {
                return ResourceManager.GetString("TxtHappyMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have another great day and keep up with your treatment..
        /// </summary>
        internal static string TxtIamOKMood_en {
            get {
                return ResourceManager.GetString("TxtIamOKMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TxtNervousMood_en {
            get {
                return ResourceManager.GetString("TxtNervousMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimistic - Your role in treatment is very important. You are 1 day closer today to the final goal..
        /// </summary>
        internal static string TxtOptimisticMood_en {
            get {
                return ResourceManager.GetString("TxtOptimisticMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybe you have had a hard day today? Try to do something you enjoy and keep your normal treatment routine..
        /// </summary>
        internal static string TxtSadMood_en {
            get {
                return ResourceManager.GetString("TxtSadMood_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prescription(s) for the frame ID A have been updated.
        /// </summary>
        internal static string UpdatePrescriptionAlertMessage_en {
            get {
                return ResourceManager.GetString("UpdatePrescriptionAlertMessage_en", resourceCulture);
            }
        }
    }
}
