// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CertificateBinDTO
    {
        /// <summary>
        /// Initializes a new instance of the SigningCertificateDTO class.
        /// </summary>
        public CertificateBinDTO() { }


        /// <summary>
        /// Binary certificate.
        /// </summary>
        public byte[] Certificate { get; set; }



        /// <summary>
        /// Flag that indicates if a new certificate exists since last update date.
        /// </summary>
        public bool Exists { get; set; }

    }
}
