// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Change
    {
        /// <summary>
        /// Initializes a new instance of the Change class.
        /// </summary>
        public Change() { }

        /// <summary>
        /// Initializes a new instance of the Change class.
        /// </summary>
        public Change(Guid? caseId = default(Guid?), string frameID = default(string), int? state = default(int?), DateTime? datetime = default(DateTime?))
        {
            CaseId = caseId;
            FrameID = frameID;
            State = state;
            Datetime = datetime;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CaseId")]
        public Guid? CaseId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FrameID")]
        public string FrameID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "State")]
        public int? State { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Datetime")]
        public DateTime? Datetime { get; set; }

    }
}
