// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class FinalTreatmentCaseDateDTO
    {
        /// <summary>
        /// Initializes a new instance of the FinalTreatmentCaseDateDTO class.
        /// </summary>
        public FinalTreatmentCaseDateDTO() { }

        /// <summary>
        /// Initializes a new instance of the FinalTreatmentCaseDateDTO class.
        /// </summary>
        public FinalTreatmentCaseDateDTO(Guid? caseUid = default(Guid?), DateTime? finalTreatmentDate = default(DateTime?))
        {
            CaseUid = caseUid;
            FinalTreatmentDate = finalTreatmentDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CaseUid")]
        public Guid? CaseUid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FinalTreatmentDate")]
        public DateTime? FinalTreatmentDate { get; set; }

    }
}
