// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PrescriptionData
    {
        /// <summary>
        /// Initializes a new instance of the PrescriptionData class.
        /// </summary>
        public PrescriptionData() { }

        /// <summary>
        /// Initializes a new instance of the PrescriptionData class.
        /// </summary>
        public PrescriptionData(IList<PrescriptionClick> parts = default(IList<PrescriptionClick>), string prescriptionNotes = default(string))
        {
            Parts = parts;
            PrescriptionNotes = prescriptionNotes;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Parts")]
        public IList<PrescriptionClick> Parts { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrescriptionNotes")]
        public string PrescriptionNotes { get; set; }

    }
}
