// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class SurgeonAddress
    {
        /// <summary>
        /// Initializes a new instance of the SurgeonAddress class.
        /// </summary>
        public SurgeonAddress() { }

        /// <summary>
        /// Initializes a new instance of the SurgeonAddress class.
        /// </summary>
        public SurgeonAddress(string addressLine1 = default(string), string addressLine2 = default(string), string city = default(string), Country country = default(Country), Guid? guidAddress = default(Guid?), string hospital = default(string), string mobilePhone = default(string), string officePhone = default(string), string postalCode = default(string), string stateProvince = default(string), string firstName = default(string), string lastName = default(string))
        {
            AddressLine1 = addressLine1;
            AddressLine2 = addressLine2;
            City = city;
            Country = country;
            GuidAddress = guidAddress;
            Hospital = hospital;
            MobilePhone = mobilePhone;
            OfficePhone = officePhone;
            PostalCode = postalCode;
            StateProvince = stateProvince;
            FirstName = firstName;
            LastName = lastName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine1")]
        public string AddressLine1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AddressLine2")]
        public string AddressLine2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "City")]
        public string City { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Country")]
        public Country Country { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GuidAddress")]
        public Guid? GuidAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hospital")]
        public string Hospital { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MobilePhone")]
        public string MobilePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OfficePhone")]
        public string OfficePhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PostalCode")]
        public string PostalCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StateProvince")]
        public string StateProvince { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstName")]
        public string FirstName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LastName")]
        public string LastName { get; set; }

    }
}
