// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class JsonResultModelBoolean
    {
        /// <summary>
        /// Initializes a new instance of the JsonResultModelBoolean class.
        /// </summary>
        public JsonResultModelBoolean() { }

        /// <summary>
        /// Initializes a new instance of the JsonResultModelBoolean class.
        /// </summary>
        public JsonResultModelBoolean(bool? success = default(bool?), string errorMessage = default(string), int? errorCode = default(int?), bool? data = default(bool?))
        {
            Success = success;
            ErrorMessage = errorMessage;
            ErrorCode = errorCode;
            Data = data;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Success")]
        public bool? Success { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorMessage")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ErrorCode")]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Data")]
        public bool? Data { get; set; }

    }
}
