// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PatientSettingsDTO
    {
        /// <summary>
        /// Initializes a new instance of the PatientSettingsDTO class.
        /// </summary>
        public PatientSettingsDTO() { }

        /// <summary>
        /// Initializes a new instance of the PatientSettingsDTO class.
        /// </summary>
        public PatientSettingsDTO(IList<PatientDiaryEvent> diaryEventList = default(IList<PatientDiaryEvent>), string pinSiteCareTime = default(string), bool? motivationalMessageFlag = default(bool?), string motivationalMessageTime = default(string), bool? personalGoalFlag = default(bool?), string culture = default(string), string timeZone = default(string), bool? pushNotificationFlag = default(bool?),string appVersion=default(string))
        {
            DiaryEventList = diaryEventList;
            PinSiteCareTime = pinSiteCareTime;
            MotivationalMessageFlag = motivationalMessageFlag;
            MotivationalMessageTime = motivationalMessageTime;
            PersonalGoalFlag = personalGoalFlag;
            Culture = culture;
            TimeZone = timeZone;
            PushNotificationFlag = pushNotificationFlag;
            AppVersion = appVersion;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DiaryEventList")]
        public IList<PatientDiaryEvent> DiaryEventList { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PinSiteCareTime")]
        public string PinSiteCareTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotivationalMessageFlag")]
        public bool? MotivationalMessageFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MotivationalMessageTime")]
        public string MotivationalMessageTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PersonalGoalFlag")]
        public bool? PersonalGoalFlag { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Culture")]
        public string Culture { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TimeZone")]
        public string TimeZone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PushNotificationFlag")]
        public bool? PushNotificationFlag { get; set; }


        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AppVersion")]
        public string AppVersion { get; set; }

    }
}
