// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PinSiteCare
    {
        /// <summary>
        /// Initializes a new instance of the PinSiteCare class.
        /// </summary>
        public PinSiteCare() { }

        /// <summary>
        /// Initializes a new instance of the PinSiteCare class.
        /// </summary>
        public PinSiteCare(int? id = default(int?), DateTime? firstDay = default(DateTime?), IList<bool?> frequency = default(IList<bool?>), IList<bool?> time = default(IList<bool?>), string patientTime = default(string), bool? enabled = default(bool?))
        {
            Id = id;
            FirstDay = firstDay;
            Frequency = frequency;
            Time = time;
            PatientTime = patientTime;
            Enabled = enabled;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FirstDay")]
        public DateTime? FirstDay { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Frequency")]
        public IList<bool?> Frequency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Time")]
        public IList<bool?> Time { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientTime")]
        public string PatientTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Enabled")]
        public bool? Enabled { get; set; }

    }
}
