// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MyHexPlanProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PrescriptionDTO
    {
        /// <summary>
        /// Initializes a new instance of the PrescriptionDTO class.
        /// </summary>
        public PrescriptionDTO() { }

        /// <summary>
        /// Initializes a new instance of the PrescriptionDTO class.
        /// </summary>
        public PrescriptionDTO(PrescriptionUpdate updates = default(PrescriptionUpdate), string sign = default(string))
        {
            Updates = updates;
            Sign = sign;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Updates")]
        public PrescriptionUpdate Updates { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sign")]
        public string Sign { get; set; }

    }
}
