//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatientApp.UITest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackdoorAndroid {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BackdoorAndroid() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PatientApp.UITest.Resources.BackdoorAndroid", typeof(BackdoorAndroid).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAndroidVersion.
        /// </summary>
        public static string GetAndroidVersion {
            get {
                return ResourceManager.GetString("GetAndroidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetBadgeStrutsAdj.
        /// </summary>
        public static string GetBadgeStrutsAdj {
            get {
                return ResourceManager.GetString("GetBadgeStrutsAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetDoneList.
        /// </summary>
        public static string GetDoneList {
            get {
                return ResourceManager.GetString("GetDoneList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFrameStrutsAdj.
        /// </summary>
        public static string GetFrameStrutsAdj {
            get {
                return ResourceManager.GetString("GetFrameStrutsAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSelectedStrutBackgroundImageName.
        /// </summary>
        public static string GetSelectedStrutBackgroundImageName {
            get {
                return ResourceManager.GetString("GetSelectedStrutBackgroundImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSelectedStrutDirectionImage.
        /// </summary>
        public static string GetSelectedStrutDirectionImage {
            get {
                return ResourceManager.GetString("GetSelectedStrutDirectionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetShoppingListCheckBoxStatus.
        /// </summary>
        public static string GetShoppingListCheckBoxStatus {
            get {
                return ResourceManager.GetString("GetShoppingListCheckBoxStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetToDoList.
        /// </summary>
        public static string GetToDoList {
            get {
                return ResourceManager.GetString("GetToDoList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetSendNotifications.
        /// </summary>
        public static string SetSendNotifications {
            get {
                return ResourceManager.GetString("SetSendNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTestMode.
        /// </summary>
        public static string SetTestMode {
            get {
                return ResourceManager.GetString("SetTestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTestScannedQrCode.
        /// </summary>
        public static string SetTestScannedQrCode {
            get {
                return ResourceManager.GetString("SetTestScannedQrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetTimeNow_SystemUtility.
        /// </summary>
        public static string SetTimeNow_SystemUtility {
            get {
                return ResourceManager.GetString("SetTimeNow_SystemUtility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulateScannedQrCode.
        /// </summary>
        public static string SimulateScannedQrCode {
            get {
                return ResourceManager.GetString("SimulateScannedQrCode", resourceCulture);
            }
        }
    }
}
