// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PatientApp.RESTProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CaseData
    {
        /// <summary>
        /// Initializes a new instance of the CaseData class.
        /// </summary>
        public CaseData() { }

        /// <summary>
        /// Initializes a new instance of the CaseData class.
        /// </summary>
        public CaseData(int? anatomiesType = default(int?), int? boneTypeSegment = default(int?), string frameID = default(string), string name = default(string), string number = default(string))
        {
            AnatomiesType = anatomiesType;
            BoneTypeSegment = boneTypeSegment;
            FrameID = frameID;
            Name = name;
            Number = number;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AnatomiesType")]
        public int? AnatomiesType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BoneTypeSegment")]
        public int? BoneTypeSegment { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FrameID")]
        public string FrameID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Number")]
        public string Number { get; set; }

    }
}
