// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PatientApp.RESTProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PackageUpdate
    {
        /// <summary>
        /// Initializes a new instance of the PackageUpdate class.
        /// </summary>
        public PackageUpdate() { }

        /// <summary>
        /// Initializes a new instance of the PackageUpdate class.
        /// </summary>
        public PackageUpdate(IList<Prescription> prescriptions = default(IList<Prescription>), string sign = default(string))
        {
            Prescriptions = prescriptions;
            Sign = sign;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Prescriptions")]
        public IList<Prescription> Prescriptions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sign")]
        public string Sign { get; set; }

    }
}
