// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PatientApp.RESTProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Prescription
    {
        /// <summary>
        /// Initializes a new instance of the Prescription class.
        /// </summary>
        public Prescription() { }

        /// <summary>
        /// Initializes a new instance of the Prescription class.
        /// </summary>
        public Prescription(CaseData caseData = default(CaseData), PrescriptionData prescriptionData = default(PrescriptionData), Schedule scheduleInfo = default(Schedule))
        {
            CaseData = caseData;
            PrescriptionData = prescriptionData;
            ScheduleInfo = scheduleInfo;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CaseData")]
        public CaseData CaseData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrescriptionData")]
        public PrescriptionData PrescriptionData { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ScheduleInfo")]
        public Schedule ScheduleInfo { get; set; }

    }
}
