// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PatientApp.RESTProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Schedule
    {
        /// <summary>
        /// Initializes a new instance of the Schedule class.
        /// </summary>
        public Schedule() { }

        /// <summary>
        /// Initializes a new instance of the Schedule class.
        /// </summary>
        public Schedule(IDictionary<string, bool?> correctionTimes = default(IDictionary<string, bool?>), DateTime? dateOfTreatmentStart = default(DateTime?), DateTime? finalTreatmentDate = default(DateTime?), bool? isApplyLengtheningShorteningFirst = default(bool?), int? latencyDays = default(int?), DateTime? surgeryDate = default(DateTime?))
        {
            CorrectionTimes = correctionTimes;
            DateOfTreatmentStart = dateOfTreatmentStart;
            FinalTreatmentDate = finalTreatmentDate;
            IsApplyLengtheningShorteningFirst = isApplyLengtheningShorteningFirst;
            LatencyDays = latencyDays;
            SurgeryDate = surgeryDate;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CorrectionTimes")]
        public IDictionary<string, bool?> CorrectionTimes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateOfTreatmentStart")]
        public DateTime? DateOfTreatmentStart { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FinalTreatmentDate")]
        public DateTime? FinalTreatmentDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsApplyLengtheningShorteningFirst")]
        public bool? IsApplyLengtheningShorteningFirst { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LatencyDays")]
        public int? LatencyDays { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SurgeryDate")]
        public DateTime? SurgeryDate { get; set; }

    }
}
