// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PatientApp.RESTProxies.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Strut
    {
        /// <summary>
        /// Initializes a new instance of the Strut class.
        /// </summary>
        public Strut() { }

        /// <summary>
        /// Initializes a new instance of the Strut class.
        /// </summary>
        public Strut(int? acute = default(int?), int? click = default(int?), int? gradual = default(int?), int? strutNumber = default(int?), int? strutSize = default(int?), int? total = default(int?))
        {
            Acute = acute;
            Click = click;
            Gradual = gradual;
            StrutNumber = strutNumber;
            StrutSize = strutSize;
            Total = total;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Acute")]
        public int? Acute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Click")]
        public int? Click { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Gradual")]
        public int? Gradual { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StrutNumber")]
        public int? StrutNumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StrutSize")]
        public int? StrutSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Total")]
        public int? Total { get; set; }

    }
}
